### ISSUE TITLE
Crypto monitor job does not start

### ISSUE THREAD

**Issue by mikelamutxastegi** [lamassuiot/lamassu-helm#56]
Hi!

I'm doing different tests checking that the CA certificate monitoring job works but it seems I can't make this job to start. 

 Does the [CA ConfigMap](https://github.com/lamassuiot/lamassu-helm/blob/6d36902e29959c476008789202985999815cfe68/charts/lamassu/templates/ca-configmap.yml) correctly reference the certificate monitoring job properties? 

```    
crypto_monitoring:
      enabled: true
      frequency: "{{ .Values.services.ca.monitoring.frequency }}"
      automatic_ca_rotation:
        enabled: false
        renewal_delta: "1d"
```

crypto_monitoring property should not be named now certificate_monitoring_job?

```    
certificate_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.ca.monitoring.frequency }}"
      automatic_ca_rotation:
        enabled: false
        renewal_delta: "1d"
```

This is what I'm seeing in the CA service logs, even if my config states that crypto_monitoring should be enabled.

![Image](https://github.com/user-attachments/assets/ccfe38b9-0511-49d3-89c7-02ed281fe01a)
